const TOGGLE_DARKNESS = 'TOGGLE_DARKNESS';
const PLAYER_MOVE = 'PLAYER_MOVE';
const DOWN_STAIRS = 'DOWN_STAIRS';
const FIGHT = 'FIGHT';
const EAT = 'EAT';
const PICKUP = 'PICKUP';
const SET_MESSAGE = 'SET_MESSAGE';
